services:
  db:
    image: postgres:16
    container_name: group7_psql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: group7_db
    volumes:
      - group7_pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "127.0.0.1:6666:5432"
    restart: "no"

  redis:
    image: redis:7
    container_name: group7_redis
    ports:
      - "127.0.0.1:6667:6379"
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: group7_backend

    volumes:
      - ./backend:/app

    env_file:
      - ./backend/.env.docker

    depends_on:
      - db
      - redis

    # 一定要確認你的 Nest 是跑在 8000
    ports:
      - "127.0.0.1:8000:8000"

    command: node dist/main.js
    restart: "no"

  frontend:
    build: ./frontend
    container_name: group7_frontend
    ports:
      - "127.0.0.1:5173:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.docker

    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro

    restart: "no"

volumes:
  group7_pgdata:
